---
# tasks file for caddy

- name: Install dependencies
  package:
    name:
      - debian-keyring 
      - debian-archive-keyring
      - apt-transport-https
      - gpg
      - curl
  when: ansible_facts['os_family'] == "Debian"

- name: Check if the gpg key is installed
  stat:
    path: /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  register: caddy_gpg
  when: ansible_facts['os_family'] == "Debian"

- name: Install GPG Key
  shell: "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg"
  when:
    - ansible_facts['os_family'] == "Debian"
    - not caddy_gpg.stat.exists

- name: Check if caddy's repo is installed
  stat:
    path: /etc/apt/sources.list.d/caddy-stable.list
  register: caddy_repo
  when: ansible_facts['os_family'] == "Debian"

- name: Install Caddy repo
  shell: "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' > /etc/apt/sources.list.d/caddy-stable.list"
  when:
    - ansible_facts['os_family'] == "Debian"
    - not caddy_repo.stat.exists

- name: Update cache apt
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Installation du package Caddy
  package: 
   name: caddy
   state: present

- name: Configuration du Caddyfile 
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: 0644
  notify: restart caddy
